### ISSUE TITLE
JS error when marking files are revirwed

### ISSUE THREAD

**Issue by chai-deshpande** [reywood/bitbucket-pr-review#9] opened 2018-01-29 18:04 UTC
![image](https://user-images.githubusercontent.com/5366467/35526252-bcfcbe5c-051e-11e8-85c1-d2a55099dd6b.png)

Please see the call stack of the exception while clicking the "Done Reviewing" button.

**Comment by VictorQRS** [comment] 2018-03-07 13:53
This is also happening to me. Is there any progress regarding this issue?

**Comment by timzap** [comment] 2018-06-01 08:44
The error occurs when the path to a file (including the filename) has a space in it.

**Comment by timbeadle** [comment] 2018-10-02 08:48
@timzap That makes #13 a duplicate of this issue, then.

**Closed as completed** 2018-10-12 22:14 UTC

**Comment by reywood** [comment] 2018-10-12 22:25
Thanks to @timzap for the PR. Finally got this merged and put a new version up.
